version: '3.7'

services:

  mysql:
    image: 'mysql:5.7'
    restart: always
    container_name: microservice_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: microservice_sqlserver
    volumes:
      - dbdata:/var/opt/mssql

  mongodb:
    image: mongo
    container_name: microservice_mongo

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: microservice_rabbitmq

  redis:
    image: redis:alpine
    container_name: microservice_redis

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.8.0'
    container_name: microservice_elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: 'docker.elastic.co/logstash/logstash:7.8.0'
    container_name: microservice_logstash
    depends_on:
      - elasticsearch

  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.8.0'
    container_name: microservice_kibana
    depends_on:
      - elasticsearch
        
volumes:
  dbdata:
  esdata: